name: validation
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validation:
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    container:
      # use container image for tools already installed
      image: docker.io/ajinka4ridecell/infra-auth:v2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check modified files for any changes to IBM clusters
        id: check-cluster-changes
        run: |
          # Added to slove fatal: detected dubious ownership in repository at '/__w/infra-auth/infra-auth' error.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch origin main

          git config --global diff.dyff.command 'dyff_between() { dyff --color on between --omit-header "$2" "$5"; }; dyff_between' && \
          echo '*.yml diff=dyff' >> .gitattributes 

          echo "-------- Testing diff start ------------"
          git diff --name-only origin/main...HEAD -- 'users/*.yml'
          echo "-------- Testing diff end ------------"


          for file in $(git diff --name-only origin/main...HEAD -- 'users/*.yml'); do

            echo "-------- Testing diff in for loop start ------------"
            git diff --ext-diff origin/main...HEAD -- "$file"
            echo "-------- Testing diff in for loop end ------------"

            if git diff --ext-diff origin/main...HEAD -- "$file" | grep -q "ibm-plat-fr2-01"; then
              CHANGED=true
              break
            fi
          done
          echo "changed_file_name"=$file >> $GITHUB_OUTPUT
          echo "cluster_changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: steps.check-cluster-changes.outputs.cluster_changed == 'true' && github.event_name == 'pull_request'
        run: |
          curl -sX POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"body":"⚠️ Detected changes in `IBM BNPP` clusters. Please ensure the changes are authorized.","event":"COMMENT","comments":[{"path":"'${{ steps.check-cluster-changes.outputs.changed_file_name }}'","position":1,"body":"Please follow the access policies for the IBM BNPP infra."}]}'
