name: validation
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
   validation:
    permissions:
        id-token: write
        contents: read
        issues: write
        pull-requests: write
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 2

        -  name: Setup dyff diff tool
           run: |
            curl -L https://github.com/homeport/dyff/releases/download/v1.7.1/dyff_1.7.1_linux_amd64.tar.gz -o dyff.tar.gz
            tar -zxvf dyff.tar.gz
            cp dyff /usr/local/bin/dyff

            cd "$GITHUB_WORKSPACE"
            export GIT_DIR="$GITHUB_WORKSPACE/.git"
            export GIT_WORK_TREE="$GITHUB_WORKSPACE"

            git config --file "$GIT_DIR/config" diff.dyff.command 'dyff_between() { dyff --color on between --omit-header "$2" "$5"; }; dyff_between'
            echo '*.yml diff=dyff' >> .gitattributes

        -  name: Check modified files for any changes to k8s.ibm-plat-fr2-01-workload
           id: check-cluster-changes
           run: |
            # Added to slove fatal: detected dubious ownership in repository at '/__w/infra-auth/infra-auth' error.
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git fetch origin main
            for file in $(git diff --name-only origin/main...HEAD -- '*.yml'); do
                if git diff --ext-diff origin/main...HEAD -- "$file" | grep -q 'k8s\.ibm-plat-fr2-01-workload'; then
                CHANGED=true
                break
                fi
            done

            echo "cluster_changed=$CHANGED" >> $GITHUB_OUTPUT

        -   name: Comment on PR
            if: steps.check-cluster-changes.outputs.cluster_changed == 'true' && github.event_name == 'pull_request'
            run: |
                FILE="k8s/ibm-plat-fr2-01-workload.yaml"
                COMMENT="⚠️ Detected changes in \`ibm-plat-fr2-01-workload\`. Please ensure the changes are authorized."

                # Get the diff position (this uses jq)
                POSITION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github+json" \
                    https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
                    | jq ".[] | select(.filename == \"$FILE\") | .patch" \
                    | grep -n '^+' | head -1 | cut -d':' -f1)

                if [ -z "$POSITION" ]; then
                    echo "No changes found in file."
                    exit 0
                fi

                # Post the inline comment
                curl -s -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github+json" \
                    https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments \
                    -d @- <<EOF
                {
                "body": "$COMMENT",
                "commit_id": "${{ github.event.pull_request.head.sha }}",
                "path": "$FILE",
                "side": "RIGHT",
                "position": $POSITION
                }
                EOF
                        