name: Create PR on behalf of Workflows

on:
  workflow_dispatch:
    inputs:
      REPOSITORY:
        description: 'The Ridecell repository where PR should be created, in the format Ridecell/{repo_name}'
        required: true
      REF:
        description: 'The desired branch/tag/sha to merge into main/master'
        required: true
      TITLE:
        description: 'Title for the Pull Request'
        required: true
      BODY:
        description: 'Text body for the Pull Request'
        required: false
        default: ''
      SLACK_CHANNEL:
        description: 'Slack channel to be notified of PR creation'
        required: false
        default: 'devops-eng-private'

  push:
    branches:
      - main  # You can change this to the branch where updates are made


jobs:
  create-pr:
    runs-on: ubuntu-latest
    name: Create Pull Request

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This step checks out your repository's code.

    # - name: Display Workflow Inputs
    #   run: |
    #     echo '${{ toJSON(github.event.inputs) }}'

    # - name: Format inputs for postdata body
    #   id: post-body
    #   run: |
    #     # It seems although input BODY was received in JSON format (e.g. newlines escaped),
    #     # the escaped values gets converted. Hence, we need to format it to JSON again for
    #     # building our postData body in the next step.
        
    #     echo PR_BODY=${{ toJSON(inputs.BODY) }} >> $GITHUB_OUTPUT

    # - name: Commit and push changes
    #   run: |
    #     git config --global user.name "ajinkyak423"
    #     git config --global user.email "ajinkyakumbhar423@gmail.com"

    #     git add .
    #     git commit -m "Auto-generated PR"
    #     git push origin HEAD:main

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.MY_GITHUB_ACTION_TOKEN }}
    #     branch: main  # Specify the branch you want to create a PR against.
    #     title: "Auto-generated PR"
    #     body: "This PR was automatically generated by a GitHub Actions workflow."

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.MY_GITHUB_ACTION_TOKEN }}
        commit-message: "Automated PR: Update file"
        branch: main  # The branch you want to create the PR against
        title: "Automated PR: Update file"
        body: |
          This PR updates the file via GitHub Actions.

        base: main  # The target branch for the PR
        files: kustomization.yml  # The path to the updated file

    - name: Notify Devops of PR
      id: slack-notify
      uses: sonots/slack-notice-action@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      with:
        username: GithubActions
        status: custom
        payload: |
            {
                "channel": "#${{ inputs.SLACK_CHANNEL }}",
                "text": "New version available \nAutomated Pull Request Created",
                "blocks": [
                {
                    "type": "header",
                    "text": {
                    "type": "plain_text",
                    "text": "New version availabl"
                    }
                }
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Pull Request:\n${{ inputs.TITLE }}>"
                  }
                }
              ]
            }