name: slack-notify
on:
  push:
   
jobs:
  slack-notify:
    runs-on: ubuntu-latest
    container:
        image: ajinka4ridecell/krr:v11

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: create csv
        run: |
          touch test.csv
          ls -ll /usr/local/bin/
          pip install -r requirements.txt

      - name: Send CSV to Slack
        run: |
            python temp/krr_batch_processing.py