name: Create Pull Request

on:
  push:
    branches:
      - main  # Replace with the branch where you want to create a PR

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.MY_GITHUB_ACTION_TOKEN }}
          title: "Feature: Update file.txt"
          body: "This PR updates file.txt with the latest changes."
          branch: feature-branch  # Replace with the branch name where changes were pushed
