name: slack-notify
on:
  push:
   
jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: create csv
        run: |
          touch test.csv

      - name: Send CSV to Slack
        run: |
            CSV_FILE=$(ls *.csv)
            curl -F file=test.csv -F "initial_comment=Here is the generated CSV file" -F channels=C05QXU43GUQ -H "Authorization: Bearer $SLACK_CSV_APP_TOKEN" https://slack.com/api/files.upload
        env:
            SLACK_CSV_APP_TOKEN: ${{ secrets.SLACK_CSV_APP_TOKEN }}
        