name: slack-notify
on:
  push:
   
jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: create csv
        run: |
          touch test.csv

      - name: Send CSV to Slack
        run: |
            pip install ruamel.yaml==0.18.6 pandas==1.5.3 kubernetes==29.0.0 slack_sdk==3.21.3
            python temp/krr_batch_processing.py