name: test-hello

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  hello-job-1:
    name: hello-job-1
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '00 12 * * *'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Say hello
        run: echo "hello ajinkya hi"

  hello-job-2:
    name: hello-job-2
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '01 12 * * *'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Say hello
        run: echo "hello ajinkya hi"

  hello-job-3:
    name: hello-job-3
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '02 12 * * *'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Say hello
        run: echo "hello ajinkya hi"
