name: Update File

on:
  push:
    branches:
      - feature-branch

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Make Changes to File
        run: |
          # Make your desired changes to the file here
          echo "Updated content" > test.txt

      - name: Commit Changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add test.txt
          git commit -m "Update file via GitHub Actions"
          git push origin feature-branch
