name: Make Changes

on:
  push:
    branches:
      - main  # Replace with the branch where you want to make changes

jobs:
  make-changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Make Changes
        run: |
          # Make your desired changes to the file(s) here
          echo "This is a change" >> file.txt

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Made changes via GitHub Actions"
          
      - name: Push Changes to Feature Branch
        run: git push origin ${{ github.ref }}
