name: Update File and Create Pull Request

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger updates on

jobs:
  update-file-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Update File
        run: |
          # Add your script or command to update the file here
          # For example, to append some text to a file:
          echo "New content" >> yourfile.txt

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b feature/update-file  # Create a new branch for the changes
          git add yourfile.txt
          git commit -m "Update file via GitHub Actions"

      - name: Pull Latest Changes from Main
        run: |
          git fetch origin main:main
          git checkout main
          git pull origin main

      - name: Switch Back to Feature Branch
        run: |
          git checkout feature/update-file
          git rebase main
          git push origin feature/update-file --force  # Force push to the new branch

      - name: Create Pull Request
        uses: actions/github-script@v5
        with:
          script: |
            const github = require('@actions/github');
            const octokit = github.getOctokit(process.env.MY_GITHUB_ACTION_TOKEN);

            const newPullRequest = await octokit.pulls.create({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              title: 'Automated PR: Update file',
              head: 'feature/update-file',  // The new branch with changes
              base: 'main',  // The target branch for the PR (main in this case)
              body: 'This PR updates the file via GitHub Actions.',
            });
            console.log(`Created PR: ${newPullRequest.data.html_url}`);
