name: only Monitor Runner Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      DESIRED_VERSION:
        description: 'GitHub-Runner version to install'
        required: false

jobs:
  monitor-releases:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Release Information
        id: release-info
        run: |
          chmod +x ./get_release.sh
          ./get_release.sh
          # CURRENT_VERSION=${CURRENT_VERSION}
          # latest_release=${latest_release}
          # previous_major_version=${previous_major_version}
          # latest_release_previous_major=${latest_release_previous_major}
          # release_data=${release_data}
          
      - name: Notify about new release
        if: github.event.inputs.DESIRED_VERSION == null
        run: |
          notify=${{steps.release-info.outputs.notify}}
          if $notify; then
            postData='{
              "ref": "main",
              "inputs": {
                "REPOSITORY": "${{ github.repository }}",
                "REF": "Runner-Update",
                "TITLE": "GitHub action runner update",
                "BODY": "Current Version: ${{ env.CURRENT_VERSION }}\nLatest Release: ${{ env.latest_release }}\nPrevious Major Version: ${{ env.previous_major_version }}\nLatest Release from Previous Major: ${{ env.latest_release_previous_major }}",
                "SLACK_CHANNEL": "actions-notif"
              }
            }'
            # Note that postData BODY can be sensitive and may cause workflow to
            # fail if the content of the changelog includes char sequences that
            # github actions may interpret as needing substition
            # (e.g. if dollar-open-brackets-close-brackets sequence is seen)
            curl -X POST \
            -d "${postData}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_GITHUB_ACTION_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ajinkyak423/actions-poc/actions/workflows/create-pr.yml/dispatches
          else
            echo "Notify value: $notify"
          fi

      - name: Check if Manual Dispatch and DESIRED_VERSION provided
        id: manual-check
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' && -z ${{ github.event.inputs.DESIRED_VERSION }} ]]; then
            echo "Skipping workflow because DESIRED_VERSION was not provided during manual dispatch."
            exit 0
          fi

      - name: Update File
        if: github.event.inputs.DESIRED_VERSION
        run: |
          python update_image_tag.py
          
      - name: Commit Changes
        if: github.event.inputs.DESIRED_VERSION
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b Runner-Update  # Create a new branch for the changes
          git add .
          git commit -m "Update file via GitHub Actions"

      - name: Pull Latest Changes from Main
        if: github.event.inputs.DESIRED_VERSION
        run: |
          git fetch origin main:main
          git checkout main
          git pull origin main

      - name: Push Changes to New Branch
        if: github.event.inputs.DESIRED_VERSION
        run: |
          git checkout Runner-Update
          git rebase main
          git push origin Runner-Update --force  # Force push to the new branch
                
      - name: Create PR and Notify via Github-actions
        if: github.event.inputs.DESIRED_VERSION
        run: |
          postData='{
            "ref": "main",
            "inputs": {
              "REPOSITORY": "${{ github.repository }}",
              "REF": "Runner-Update",
              "TITLE": "GitHub action runner update",
              "BODY": "Current Version: ${{ env.CURRENT_VERSION }}\nLatest Release: ${{ env.latest_release }}\nPrevious Major Version: ${{ env.previous_major_version }}\nLatest Release from Previous Major: ${{ env.latest_release_previous_major }}",
              "SLACK_CHANNEL": "actions-notif"
            }
          }'
          # Note that postData BODY can be sensitive and may cause workflow to
          # fail if the content of the changelog includes char sequences that
          # github actions may interpret as needing substition
          # (e.g. if dollar-open-brackets-close-brackets sequence is seen)
          curl -X POST \
          -d "${postData}" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_ACTION_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ajinkyak423/actions-poc/actions/workflows/create-pr.yml/dispatches